### ISSUE TITLE
no butInstall button

### ISSUE THREAD

**Issue by rwoodnz** [tretapey/svelte-pwa#1]
install.js on line 4 looks for an element butInstall, which doesn't exist in the code.

**Comment by rawoke083** [comment]
Same !

**Comment by HannesGitH** [comment]
you could just put an 
```html
<button id="butInstall" hidden>installieren</button>
```
in the index.html body 

**but** honestly i dont think the whole install.js is a better UX, so just remove 
```html
<script src="install.js"></script>
```
alltogether ( and the whole install.js script with it)

**Comment by tretapey** [comment]
Hi all, let me check this issue.. Would you make a PR for this?

**Comment by tretapey** [comment]
This changes will be ready on a next release

**Comment by tretapey** [comment]
Released in v.1.0.3
